name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Build
        run: swift build -C ClipboardHistoryFixed
      - name: Test
        run: swift test -C ClipboardHistoryFixed
      - name: Build (SPM)
        run: swift build --build-tests --package-path ClipboardHistoryFixed
      - name: Run tests (SPM)
        run: swift test --enable-code-coverage --package-path ClipboardHistoryFixed